/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import static Interfaces.CargarRed.grafoGestion;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Alesia Castro
 */
public class Coberturas extends javax.swing.JFrame {

    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    public static Menu v1;

    public Coberturas(Menu v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.ActualizarComboBox();
    }
    
    public void ActualizarComboBox(){
        modeloCombo.removeAllElements();
        if (grafoGestion.verEstacionesConSucursal()!= null) {
            for (int i = 0; i < grafoGestion.verEstacionesConSucursal().getSize(); i++) {
                String nombre = (String) grafoGestion.verEstacionesConSucursal().getValor(i);
                modeloCombo.addElement(nombre);
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estacionInicio = new javax.swing.JComboBox<>();
        verificarCobertura = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoCobertura = new javax.swing.JComboBox<>();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setText("COBERTURAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setText("Verificar Cobertura de una Ciudad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        estacionInicio.setModel(modeloCombo);
        estacionInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionInicioActionPerformed(evt);
            }
        });
        jPanel1.add(estacionInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 210, -1));

        verificarCobertura.setBackground(new java.awt.Color(0, 204, 204));
        verificarCobertura.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        verificarCobertura.setText("Verificar Cobertura");
        verificarCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarCoberturaActionPerformed(evt);
            }
        });
        jPanel1.add(verificarCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N
        jLabel3.setText("Ciudad de Inicio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel4.setText("Elegir Tipo de Recorridos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        tipoCobertura.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N
        tipoCobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DFS", "BFS" }));
        jPanel1.add(tipoCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, -1));

        volver.setBackground(new java.awt.Color(0, 204, 204));
        volver.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estacionInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacionInicioActionPerformed

    private void verificarCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarCoberturaActionPerformed
        if (tipoCobertura.getSelectedItem().equals("BFS")) {
            String estacion = (String) estacionInicio.getSelectedItem();
            grafoGestion.calcularCoberturaBFS(estacion);
        } else {
            String estacion = (String) estacionInicio.getSelectedItem();
            grafoGestion.calcularCoberturaDFS(estacion);
        }
    }//GEN-LAST:event_verificarCoberturaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        this.v1.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coberturas(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estacionInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tipoCobertura;
    private javax.swing.JButton verificarCobertura;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
